name: Start and Stop GCP VM Instance

on:
  workflow_dispatch:
  
jobs:
  start-vm:
    runs-on: ubuntu-latest
    permissions:
       contents: "read"
       id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/767086571535/locations/global/workloadIdentityPools/wif-ga-pool/providers/github"
          service_account: 'id-wf-ga-sa@model-height-439805-h4.iam.gserviceaccount.com'
      - name: Start GCE VM
        run: |
          gcloud compute instances start wif-ga-sa --zone=us-central1-c
  stop-vm:
     needs: start-vm
     runs-on: ubuntu-latest
     permissions:
       contents: "read"
       id-token: "write"
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
           
       - name: Authenticate to GCP
         uses: google-github-actions/auth@v2
         with:
           workload_identity_provider: "projects/767086571535/locations/global/workloadIdentityPools/wif-ga-pool/providers/github"
           service_account: id-wf-ga-sa@model-height-439805-h4.iam.gserviceaccount.com
       - name: Start GCE VM
         run: |
           gcloud compute instances stop wif-ga-sa --zone=us-central1-c
                
     
